#Water constants
WATER_I2C_ADDRESS=0x48
WATER_SENSOR_ANALOG_PIN_INPUT = 0x40 # water sensor
WATER_SERVO_PIN = 7
WATER_SERVO_NUMBER = 0 # Pin 7 is mapped to value 0
WATER_SERVO_ANGLE_CLOSED = 240
WATER_SERVO_ANGLE_OPEN = 170
